### ISSUE TITLE
Create Android Build Of Project

### ISSUE THREAD

**Issue by cplaguna-audio** [GTCMT/MusicEnsembleEdu#2]

**Comment by jpedrocm** [comment]
Android build is compilable in my Linux VM, and is running a Nexus 4. The configuration was done manually as it seemed to exist no way of linking the external libraries with the Projucer.

Next steps are:
- Automate the process of rewriting Android files and project structure because the Projucer rewrites the whole build every time you save a the .jucer file.
- Test and document the steps for creating this build in a fresh VM.

**Comment by jpedrocm** [comment]
The app also works with LG G4.

**Comment by jpedrocm** [comment]
All steps were done. Android build can be created with Mac too. Although it should work with Windows too, the JUCE devs do not recommend using the Projucer with Android Studio inside of Windows.
